modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/reoseah/catwalks-incorporated/issues"
license = "MIT"

[[mods]]
modId = "catwalksinc"
version = "${version}"
displayName = "Example Mod"
authors = "Reoseah"
description = '''
Leading industrial provider of personnel foot-traffic solutions for the construction, manufacturing and mining industries.
'''
#logoFile = ""

[[dependencies.catwalksinc]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.catwalksinc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"